### ISSUE TITLE
[Feature Request] Include server name in 2FA TOTP issuer

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1016]
**Problem description**

If a user accesses multiple vantage6 instances with two-factor authentication, the identifier for each TOTP code on their phone may look the same. It's always `vantage6 (cotopaxi): username`, so there's no easy way to distinguish the different servers unless they are running different major versions or the user has different usernames. 

**Desired solution**
A way for the server administrator to give human identifiable name to the server that is used in the issuer for the TOTP. For example, something like: `vantage6 (server_name): username`, instead of the version.

**Additional context**
Some TOTP do allow you to change part of that string at least, but that implies the user should take an extra step.

**Comment by bartvanb** [comment]
I guess it would make most sense to include a `server_name` as configuration option. I think we can put that information into the QR code easily. Alternatively, there is already the `name` configuration option that can be used directly, but that may not be a nice value always. Third option is to create a configuration option specifically for this in the `mfa` part of the configuration - but I don't think I prefer that.
