### ISSUE TITLE
[Bug] `default  argument is not documented

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1052]
**Describe the bug**
Missing function argument documentation at: https://github.com/vantage6/vantage6/blob/fdaf7c3dcb653f89fd74f3ebb4d2cce3c80516ef/vantage6-algorithm-tools/vantage6/algorithm/tools/util.py#L53

**Comment by bartvanb** [comment]
Fixed in https://github.com/vantage6/vantage6/commit/526c9dc1d6464a3857ef2f777e599ec2b4e141d0
