### ISSUE TITLE
[Feature Request] Ability to register a node in new UI

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1122]
**Problem description**
In the new UI (4.3.0rc2), I'm unable to find how to register a node for a newly created collaboration for which node-registration was not requested. This used to be possible in the previous UI.

**Desired solution**
The ability to generate an API key (first time) in the UI via the Collaborations tab, or the Nodes tab.

**Additional context**
I typically create an organization, add a user, and hand it off to that user to let them register the node once they are ready.

Maybe a label for this issue (e.g. newUI) would be convenient? Is it researcherUI?

**Comment by frankcorneliusmartin** [comment]
tested: ✔
