### ISSUE TITLE
[Change Request] Select database to execute preprocessing on

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#1137]
**Description**
The preprocessing steps (extend and filter data) should be done on a certain algorithm database. The database(s) are set just before the preprocessing in the task create process. When creating a preprocessing step, there should be a dropdown with selected databases to choose from to do the preprocessing on. If there is only one database selected, this dropdown does not need to be there (database should be selected in the background).

Note also that preprocessing should not be visible if the algorithm uses 0 databases.

**Comment by frankcorneliusmartin** [comment]
@bartvanb I think this issue is outdated. If you agree, can you close it?

**Comment by bartvanb** [comment]
Yeah I wouldn't call it outdated but with sessions we'll have to do a lot of rework there and we don't need this separate issue
