### ISSUE TITLE
[Feature Request] Which communication protocol and serialization method is supported?

### ISSUE THREAD

**Issue by Rene36** [vantage6/vantage6#1161]
Dear Vantage6 Team,

I am currently writing a survey paper on Federated Computing. One part of it describes existing FL frameworks. Could you please let me know which communication protocol (e.g., gRPC, WebSocket, HTTP, GLOO) and serialization method (e.g., Pickle, JSON, Protobuf, FOBS) you supports I already saw in your documentation that you support gRPC, but maybe there is more.

Any help is highly appreciated.

**Comment by bartvanb** [comment]
Hi @Rene36, our infrastructure uses HTTP(S) and websockets for communication, and optionally VPN. For serialization we use JSON by default but we don't enforce this: algorithm developer can also use their own serialization method in their algorithm - as long as the different parts of the algorithm can communicate with each other it should work (though a researcher would need to deserialize themselves)

**Comment by frankcorneliusmartin** [comment]
Hi @Rene36 good to see that you've found us 😄. 

I just want to add that you can find us on Discord to have a more interactive chat: https://discord.gg/yAyFf6Y. We would be more than happy to help you collect the right information about our infrastructure. 

I close this issue for now, but feel free to open it again if you feel like it.
