### ISSUE TITLE
[DOC] unclarity about setup_encryption

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1174]
The documentation regarding setup_encryption is incomplete and unclear.

E.g. I have the possibility to do client.setup_encryption in my notebook, which seems a user client. It requires to run setup_encryption(key_file) to setup the encryption. The documentation however mentions this:
https://docs.vantage6.ai/en/main/function-docs/node.html#vantage6.node.Node.setup_encryption
Which does not mention the key_file, but also it does not mention the link to the user client.

The user client code points to:
```
    def setup_encryption(self, private_key_file: str) -> None:
        """Enable the encryption module fot the communication

        This will attach a Crypter object to the client. It will also
        verify that the public key at the server matches the local
        private key. In case they differ, the local public key is uploaded
        to the server.

        Parameters
        ----------
        private_key_file : str
            File path of the private key file

        Raises
        ------
        AssertionError
            If the client is not authenticated
        """

```
The documentation here also does not specify what key file is required. It seems a collaboration key file is required, but given that I run setup_encryption on a user client I could think I need a personal private key.

The code client.setup_encryption(config.organization_key) on https://docs.vantage6.ai/en/main/user/pyclient.html#authentication is not findable when you search setup_encryption in the search box.

**Comment by bartvanb** [comment]
This should be done together with https://github.com/vantage6/vantage6/issues/1302
