### ISSUE TITLE
[Feature Request] Give node admin option to not fallback on local image

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1200]
**Problem description**
(Low prio). A node admin might want to make sure that algorithm images are always at the latest version. And that the local image is not use in lieu of being able to reach it from the registry.

**Desired solution**
A node config option to control that.

**Additional context**
See this thread for context: https://github.com/vantage6/vantage6/pull/1196#discussion_r1559498994

**Comment by frankcorneliusmartin** [comment]
Related: #1250
