### ISSUE TITLE
[Feature Request] Select all (organizations) at task creation in the UI

### ISSUE THREAD

**Issue by anjavangestel** [vantage6/vantage6#1220]
In the UI when creating a task it would be nice if you could 'select all' when selecting organizations to include in your algorithm.

**Comment by bartvanb** [comment]
Usually, these selections are in principle not necessary as the default is to select all (if you don't provide the argument). In #1219 we aim to add the option to the UI that you don't fill in optional parameters - would that solve this issue for you?

**Comment by bartvanb** [comment]
Yes we should, I was planning on that but didn't mention it :-)

**Comment by bartvanb** [comment]
I'm going to close this, because I think now that we have default values for algorithm store function arguments implemented, the default value will be to select all organizations - so you are no longer required to select them all manually
