### ISSUE TITLE
[Bug] Reset password does not check for repeated password

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1228]
**Describe the bug**
When resetting password via forgotten password, the check for repeated password seems not enforced. It seems to just take "New password" inputted.

**To Reproduce**
Reset a password via forgotten password, getting token via email.

**Expected behavior**
Validation of the form in some way to make sure New passwords and repeated new password match before accepting new password.

**Screenshots**

![image](https://github.com/vantage6/vantage6/assets/45853121/39dbe394-3d0a-42e4-a26c-8c34249a2d72)

**Details**
 - Version 4.4.0

**Comment by bartvanb** [comment]
Oops :-)
