### ISSUE TITLE
[Bug] "Register missing nodes" shows up when there are no missing nodes

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1229]
**Describe the bug**
Very minor. "Register missing nodes" button still shows up when all nodes have already been registered. If you click it an empty file is downloaded.

**To Reproduce**
In a collaboration where all nodes have been registered, hit "Register missing nodes.

**Expected behavior**
For the button not to show up perhaps.

**Screenshots**
Example below with toy collaborations and organizations:
![image](https://github.com/vantage6/vantage6/assets/45853121/2f223bd1-3c0e-4c7c-a14f-9e025d3d0a8b)
![image](https://github.com/vantage6/vantage6/assets/45853121/37aa48bd-1570-4e36-a638-ff8da9b6f8ea)

**Details**
 - Version 4.4.0

**Comment by bartvanb** [comment]
I happened to see the same thing last week, #1225 fixes this and will be released in v4.5

**Comment by lsago** [comment]
> I happened to see the same thing last week, #1225 fixes this and will be released in v4.5

Ah, perfect, thanks!
