### ISSUE TITLE
[Bug] Unable to register node as organization admin via UI

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#1230]
**Describe the bug**
Unable to register node as organization admin via UI. The button does not show up.

**To Reproduce**
1. Create an organization, and a organization admin user for that organization.
2. Create a collaboration, but do check the box "Register nodes".
3. Log in as a user that is just the organization admin.
4. Go to collaborations and hit on a collaboration for which a node has not been created.

**Expected behavior**
Ability for the organization admin to register their own node.

**Screenshots**
![image](https://github.com/vantage6/vantage6/assets/45853121/3eabf57d-adb8-4a1c-8f5f-e18c7ecd5204)

**Details**
 - Version 4.4.0

**Additional context**
I think this was partially address here: https://github.com/vantage6/vantage6/pull/1202 . However a typical workflow for me is to let the organization admin do the registering of their node as I think it's "cleaner" than me (collab admin) generating an API I will never use.

**Comment by frankcorneliusmartin** [comment]
@lsago is this something you are going to pickup?

**Comment by bartvanb** [comment]
Discussed with @lsago, he'll not pick it up any time soon
