### ISSUE TITLE
[Bug] Proxy server reports status code 200 even when other status code is returned from the server

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1241]
**Describe the bug**

https://github.com/vantage6/vantage6/blob/b4f9676f99d5383a44780689a7dd60c67a73bb85/vantage6-node/vantage6/node/proxy_server.py#L277-L286

By doing this the `ContainerClients` will not retry the request when a non 2xx code is returned from the server.

**Comment by bartvanb** [comment]
What is happening in the ContainerClient that is relevant here? 
And am I understanding you'd want to return the original code instead of `INTERNAL_SERVER_ERROR`?

**Comment by frankcorneliusmartin** [comment]
The exception part is fine. This happens when the request succeeds non 200 code. Then the response is forwarded with a 200 code.
