### ISSUE TITLE
[Feature Request] Node's "last_seen" in UI

### ISSUE THREAD

**Issue by anjavangestel** [vantage6/vantage6#1308]
As a user of the UI I want to be able to see the "last seen" status of the nodes in my collaboration.

Implementation ideas:
Maybe somewhere in a table so I can see the status of all nodes, or maybe when you hover over a node in the collaboration page of a certain collaboration.

**Comment by frankcorneliusmartin** [comment]
Maybe do this together with #1213

**Comment by bartvanb** [comment]
> Maybe do this together with https://github.com/vantage6/vantage6/issues/1213 (although this is not directly available from the API)

I think they are rather separate from one another. But we can discuss moving that one up in the planning if you feel we need it soon.
