### ISSUE TITLE
[Bug] UI does not use correct `store_id` when multiple stores are present

### ISSUE THREAD

**Issue by wbaccinelli** [vantage6/vantage6#1420]
When trying to run a task using an algorithm from a specific store, and two stores are available, store_id 1 is always used, despite the selection of an algorithm from a different store.  

**To Reproduce**
1. Link two stores to a server
2. From the UI, create a new task using an algorithm from the store with id 2

**Expected behavior**

**Screenshots**
Task creation in the UI:
![image](https://github.com/user-attachments/assets/e4bdbbce-eb00-456f-b8e9-01287c092008)

Result in the terminal (after adding debug lines):
![image](https://github.com/user-attachments/assets/ec046d20-dc9d-4552-86f3-6443b3231869)

**Details**
 - OS: W10
 - Version 4.6.1

**Comment by bartvanb** [comment]
Thanks for reporting this :-) we'll discuss if we want to create a hotfix to fix this asap
