### ISSUE TITLE
[Bug] Tasks on collaborations with SQL datasources fail when created through the web-based UI (Related to issue #1237)

### ISSUE THREAD

**Issue by hcadavid** [vantage6/vantage6#1450]
When requesting a task execution on a collaboration with SQL data sources, through the web-based UI, issue #1237 previously closed shows up again. This doesn't happen when executing the same algorithm through the Python client. So far I've tested this with the 'Average' algorithm from the community store.

Upon further exploration, I found that after entering the SQL query on the web interface, the node tries to execute another 'algorithm' called `column_headers` from the image harbor2.vantage6.ai/algorithms/basics. This causes the problem as this containerized function does not seem to include the updated wrapper with the fix of issue #1237 (its last 'push' on harbor2 was in February 2024). There is no source code for this 'algorithm/basics' container on the vantage6 organization (I couldn't find the source code of the 'column_headers' function/algorithm), so I'm not sure how to work on a PR for this.

![image](https://github.com/user-attachments/assets/44c2ca17-3c03-4c21-ab38-7f420606fcf4)

**Comment by bartvanb** [comment]
Good find @hcadavid. Indeed we needed to update the `basics` package, I just rebuilt the docker image and pushed it. Can you check if it is resolved now?

The source code is here: https://github.com/IKNL/vantage6-algorithms/tree/basics -> we should also put this algorithm in the vantage6 Github organization and also in the community store (and document it). I don't have time for that right now but I added it to the list.

**Comment by hcadavid** [comment]
Thanks, @bartvanb, this solved the issue as expected. Now the UI gets the column names properly before running the tasks.
