### ISSUE TITLE
[Bug] v6 server start-demo-network does not exist

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#1452]
I just created a conda environment with the latest version of vantage6 (4.7) and created a local setup with `v6 dev create-demo-network`

When everything has been created it tells me the following:
```bash
Development network was set up successfully! You can now start the server and nodes with v6 server start-demo-network
```

The command `v6 server start-demo-network` does not exist though.
I suspect it's supposed to say
```bash
v6 dev start-demo-network
```

**Comment by frankcorneliusmartin** [comment]
Fixed by https://github.com/vantage6/vantage6/pull/1464
