### ISSUE TITLE
[Feature Request] Always add show logs option on task

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1472]
Now it only shows logs when a task failed.
Also, if possible, allow show logs for tasks that are completed but for which the main task is not yet done.

E.g. in the image below, also show logs for the green cells:
![image](https://github.com/user-attachments/assets/396da525-51ef-46a2-9a3b-fe37b878e98b)

**Comment by bartvanb** [comment]
Just closed this now but was already resolved in september
