### ISSUE TITLE
[DOC] instruct how to get the api key for node configuration

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1474]
The docs do not have a way to find out (easily) how to get the api key for configuring the node.

Please add instructions in this section:
https://docs.vantage6.ai/en/main/node/configure.html#all-configuration-options

E.g. the api key is node specific, it is different than the private key or public key of the organization, the api-key can be reset by the organization administrator under the nodes section in the UI.

**Comment by frankcorneliusmartin** [comment]
To clarify: How to obtain the API key from the server.

**Comment by bartvanb** [comment]
To be released in v4.9
