### ISSUE TITLE
[Bug] User interface - faulty rendering with multiple line plots

### ISSUE THREAD

**Issue by JHogenboom** [vantage6/vantage6#1511]
**The bug**
When creating multiple line plots in the UI you can not switch between them without returning back to a different visual e.g. a table or refreshing the page. 

**To reproduce the bug**
1. Place an algorithm with multiple visuals in the algorithm store
_A good example thereof `https://github.com/MaastrichtU-CDS/v6-coxph`; this repository also contains suitable test data._
2. Run and complete the task via the UI
3. Switch between the 'Cumulative Baseline Hazard' and the 'Baseline Survival Function' line plots.
_The line plot now remains the same, while we expect the curve to look significantly different._
4. Switch to the table, then switch back to the graph again.
_You should now notice that the graph does change._

**Details**
User interface (UI) version 4.7.0
Server version 4.7.0
Tested in Mozilla Firefox

**Comment by bartvanb** [comment]
As mentioned in the linked PR, I believe this to be an issue that is not specific to line plots. What happens, is that the user switches to another visualization, however, when the page completely finishes loading, the visualization is reset to the first visualization (without updating the dropdown menu). 

@JHogenboom can you verify e.g. 1) if you wait 1 min and then change to the other line, do you see the same? 2) if you switch from the first graph to the table immediately upon task completion and then wait a few seconds, is the table also replaced by the first line?

**Comment by JHogenboom** [comment]
@bartvanb In response to your comment
1) When selecting a line for visualisation, and then waiting for one minute, the line does not appear to change to the other line (and thus the same line stays).
2) Can confirm that the line (e.g. _Cumulative Baseline Hazard_) is indeed replaced by the table (e.g. _CoxPH model_) when selecting the line prior to task completion, see following screenshot.

![afbeelding](https://github.com/user-attachments/assets/ae926cb6-19b8-4b20-b37e-2e2537651732)

Hope that confirms your assumptions and thank you

**Comment by bartvanb** [comment]
Hm the second observation is what I expected but the first isn't. I'll have to have another look I guess.

**Comment by JHogenboom** [comment]
Perhaps it is good to reiterate that this is on 4.7.0, in case your expectations had 4.7.1 in mind 😄
