### ISSUE TITLE
[Bug] User with collaboration node edit permission is unable to reset API keys for other organizations

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1530]
**Describe the bug**

When I user has collaboration edit permissions for a node, he or she is unable to reset API keys as this scope is not used in the check:
https://github.com/vantage6/vantage6/blob/24a76a581354308f57b98dafc22c0a193d967151/vantage6-server/vantage6/server/resource/recover.py#L621-L627

**Details**
 - Version 4.7.1

**Comment by frankcorneliusmartin** [comment]
I see now that Bart already solved it, waiting to be merged.

**Comment by CunliangGeng** [comment]
Thanks, then I think it makes sense to merge it before the workshop?
