### ISSUE TITLE
CORS-related problem when launching a task on a v6-server upgraded to 4.8.1.

### ISSUE THREAD

**Issue by hcadavid** [vantage6/vantage6#1609]
My original server setup was based on vantage6 v4.5 (server, UI, and postgresSQL DB launched with DockerCompose. The UI worked well for basic analysis (fed-average) using encryption. However, after updating to 4.7 (the version with the SQL support we need) I'm unable to create a task on the UI after entering the task parameters ("An error occurred" message pops up). 

After updating to 4.8.1, it now fails right after clicking the +create task button. The browser console shows a CORS-related issue between the server and the community algorithm I had registered for the collaboration:

<img width="542" alt="image" src="https://github.com/user-attachments/assets/9b1041e6-9dd2-48a1-9624-3cdb5ca3c996">

The server process the task properly when requested from the CLI.

**Comment by bartvanb** [comment]
I think I know what is happening here:
- In v4.8 we updated the API path of the store to be no longer fixed at `/api` (#1524, #1581)
- As a consequence, `/api` has to be included in setting the store URL at the server

In your case, it probably means that you have to change `https://store.cotopaxi.vantage6.ai` to `https://store.cotopaxi.vantage6.ai/api` in the vantage6 server.

A workaround is therefore: delete the community algorithm store at your server from all collaborations where it was added to, and then re-add it but then including `/api` at the end.

Let's see if we can also create a migration fix in 4.8.2

**Comment by hcadavid** [comment]
You are right, thanks! I updated the path directly on the database and now it works.

**Comment by bartvanb** [comment]
I am reopening this so that we can include a migration fix to prevent others from running into this
