### ISSUE TITLE
[Bug] Inconsistency between password recovery option and user's db-schema rules.

### ISSUE THREAD

**Issue by hcadavid** [vantage6/vantage6#1611]
The V6-server SQL schema rules allows the creation of multiple users (each one with a different password) with the same email. However, the password recovery feature assumes that there will always be only one user for a given email (the password recovery option only ask for the email). 

I'm not sure what would happen upon a password recovery request in this scenario (in my case, I have the same person, with two different user names, but the same email, managing two organizations/nodes), but this will likely cause a crash or an inconsistent password update to the wrong user. For the sake of consistency either the db model should enforce a unique email address, or the recovery option should be based on the user name.

**Comment by bartvanb** [comment]
Hi @hcadavid, I think we do check for unique email addresses

- in the User SQLAlchemy model: https://github.com/vantage6/vantage6/blob/main/vantage6-server/vantage6/server/model/user.py#L65
- In the POST /user endpoint: https://github.com/vantage6/vantage6/blob/main/vantage6-server/vantage6/server/resource/user.py#L408

I don't understand which additional schema you want to modify, can you clarify?

**Comment by hcadavid** [comment]
Hi @bartvanb my apologies, I double-checked the tables and the two users (that belong to the same person) were actually using slightly different email address (I overlooked the difference). I'll close the issue.
