### ISSUE TITLE
Display task information in the node log

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#171]
It would be nice to have a little bit of “user-friendly” information in the log of the node? In particular, the id of the task being run could be supplemented by a small description of what it does (e.g., “retrieve column headers”, “Poisson model for <dataset)”) just so that the users can have at least a remote idea of the status of the analysis.

**Comment by bartvanb** [comment]
When we start a task, we only print the name of the image (and the task number) to the logs. We should add that, if we can read the input of the task, we also print the input parameters.
