### ISSUE TITLE
Support RabbitMQ from `vserver start`

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#198]
Currently, RabbitMQ functionality cannot be combined properly with `vserver start`. That is, a new dockerized RabbitMQ service is started for every `vserver start` that is executed, thus not allowing multiple servers to use the same rabbitMQ queue. This should be changed

- [x] If RabbitMQ uri is not a local address, don't create any docker containers but link the server to the RabbitMQ service
- [x] If it is a local address, check if the RabbitMQ already exists. Only create if it doesn't
- [x] On server shutdown, think about whether to keep of kill RabbitMQ. If killing, check if other servers are running.

**Comment by frankcorneliusmartin** [comment]
Openend a new issue: https://github.com/vantage6/vantage6/issues/282

Not blocking
