### ISSUE TITLE
Python client library: client.collaboration.list returns empty list

### ISSUE THREAD

**Issue by stefan-wolfsheimer** [vantage6/vantage6#230]
Using the python client library I have encountered the following inconsistent behavior: 

*steps to reproduce*
1. Create at least one collaboration (either using the shell or the client library
2. Retrieve the collaborations with the request function:
`client.request("collaboration")`
3. Attempt the get collaborations with the list function:
`client.collaboration.list()`

*expected behavior*
`client.request("collaboration")` and `client.collaboration.list()` return the same list of collaborations

*actual behavior*
`client.collaboration.list()` returns empty list

Note: `client.organization.list()` returns a list of all organizations.

**Comment by bartvanb** [comment]
Understandable assumption. In fact, I recently created an issue about the exact same problem (#199) and came to the same conclusion as you. To avoid this confusion in the future, it might be better to change the default scope to global, as that is what people expect. I'll discuss with colleagues to see if they agree
