### ISSUE TITLE
No version tags for algorithm-base docker image

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#233]
I noticed that the algorithm-base docker image is not tagged with any version.
This can be problematic if a developer wants to re-build an algorithm image for an older version of vantage6.

**Comment by frankcorneliusmartin** [comment]
The `harbor2.vantag6.ai/infrastructure/algorithm-base:[TAG]` is now tagged with the version of the vantage6-client that is installed in the image. The last build (with the latest version of the vantage6-client) is tagged with latest.
