### ISSUE TITLE
[Feature Request] Delete organizations from server

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#241]
**Problem description**
Organizations cannot be deleted at present. If they are deleted, all related resources (users, roles, tasks, etc) should also be deleted

**Desired solution**
Add possibility to the API to delete an organization

**Comment by frankcorneliusmartin** [comment]
* Should also be possible through the Python client 
* User is prompted with a summary of all to be deleted resources
* UI should be updated

options
(1) endpoint does not delete if certain param is missing
(2) do not prompt in the Python client, but let the UI do some additional calls before actually deleting it

**Comment by bartvanb** [comment]
I want this option for setting up workshop resources so I'm making it now
