### ISSUE TITLE
[Feature Request] Python version upgrade

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#251]
**Problem description**
vantage6 is only able to run on python 3.7. Newer versions run into python exceptions.

**Desired solution**
Go to Python 3.9 (or even higher?)

**Comment by bartvanb** [comment]
We should do this soon because security support for Python 3.7 ends this June: https://endoflife.date/python

**Comment by bartvanb** [comment]
This will also be a good moment to upgrade dependencies
