### ISSUE TITLE
[Feature Request] PEP8

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#254]
**Problem description**
Not all code meets the PEP8 standard

**Desired solution**
Adhere to the standard whenever possible

**Comment by frankcorneliusmartin** [comment]
AC: linter (pycodestyle fka flake8) without errors

**Comment by frankcorneliusmartin** [comment]
Related #255

**Comment by bartvanb** [comment]
Closing as we are using black now (#992)
