### ISSUE TITLE
[Feature Request] Docstring standardization

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#255]
**Problem description**
Not all docstring formatting is consistent and some are missing data

**Desired solution**
Make the consistent and add missing data (like return types)

**Additional context**
This is releted to the request to generate sphinx documentation: #249

**Comment by bartvanb** [comment]
Standardized for CLI package: #457

**Comment by bartvanb** [comment]
99% of docstrings are now complete. Closing this issue, we will complete any remnants when relevant
