### ISSUE TITLE
[Change Request] Storage location of server config files on Linux

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#269]
**Description**
Server configuration files created through `vserver new` are currently stored in the folder `/xdg`. The directory is specified [here](https://docker-py.readthedocs.io/). It seems not to be good practice to store these files there. They should be probably stored in `/etc` instead. 
We should read up on what the best practices are and then apply it. Preferably, keep using the `appdirs` package to maintain clean cross-platform path construction.

**Comment by bartvanb** [comment]
This is impossible to change with the `appdirs` package: as shown [here](https://github.com/ActiveState/appdirs) in the Linux examples, the property `site_config_dir` always refers to (subfolders of) `/etc/xdg` (unless you set an environment variable, but that's worse).
So we need to consider if we want this rather than using the appdirs package.

**Comment by bartvanb** [comment]
Had another look at this

- the `/etc/xdg` is default system directory config dir according to the [XDG Base Directories specification](https://wiki.archlinux.org/title/XDG_Base_Directory)
- That spec is followed by appdirs
- Systems can overwrite the `/etc/xdg` with an envvar

So it makes sense that appdirs is using that directory, no use in creating an issue there.

However, looking at the generic [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/fhs.shtml) for Unix:

- Config files should be stored in `/etc/` and preferably subdirs of that
- in our case that would be `/etc/vantage6`

That would be the 'normal' thing to do, but it doesn't follow the specification appdirs is following.
What we could do, is simply overwrite the `xdg` dir with `etc/vantage6`, or leave it as is

**Comment by frankcorneliusmartin** [comment]
Checked. 

```
[info ] - New configuration created: /etc/vantage6/server/henk.yaml
[info ] - You can start the server by running vserver start
``` 

Also when the folder does not exist yet:

```
[warn ] - Target directory '/etc/vantage6' for configuration file does not exist.
[error] - Your user does not have write access to all folders. Exiting
[info ] - Create a new server using 'vserver new --user' instead!
```
