### ISSUE TITLE
[Bug] Rabbitmq URI does not support hostnames and does require a very specific local hostname

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#282]
**Describe the bug**

_Specific local hostname_
In the case you want to use a local rabbitmq container the _host_ part of the `rabbitmq_uri` needs to be in the following format: `vantage6-[SERVER_NAME]-rabbitmq`. If this name is incorrect this leads to a lot of errors when starting (and stopping) the server. 

_hostnames_
https://github.com/vantage6/vantage6/blob/01e55ea12be82ed9eddf3f7db11aa6d02d1b2bdb/vantage6/vantage6/cli/rabbitmq/__init__.py#L33

The assumption ip-address == not local address is not true when:
1. The rabbitmq service has a hostname
2. when using localhost

Another usefull thing would be that the CLI is more helpful when using a local rabbitmq instance (e.g. prefilling a valid URI). This would make testing easier and gives users a better hint how the URI should be formatted.

**Comment by bartvanb** [comment]
Preliminary work on `change/rabbitmq-hostname-check-improved`
