### ISSUE TITLE
[Change Request] Remove unneeded code from the Makefile

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#284]
**Description**
The main Makefile contains a lot of helper commands to manage multiple repositories. This is nog longer needed as we merged them to a single repository. Note that some of the commands are still used (also in the Github actions) so becareful which to remove...

**Comment by bartvanb** [comment]
I've already done some cleaning of the Makefile directly [after we merged](https://github.com/vantage6/vantage6/commit/93ae7ce0604d14baaa3308d5b4c6b4a9893900ac).

I wonder what you're suggesting to remove. Most (all) things that are in there now can/are still used. E.g. when installing all dependencies, there are still separate dependencies in each subfolder, so we need to `cd` into each. Also, we still make PyPi releases for each version of server, node, CLI, etc. 
We could remove part of these functionalities, but that is probably a lot more complicated than removing commands from the central Makefile.
