### ISSUE TITLE
[Bug] KeyError: 'sub' when connecting to vantage6 server

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#285]
**Describe the bug**
I tried to connect to my vantage6 server with the new client version `3.3.0` and I got the following message:
```python
Authenticating user <USERNAME>...
Successfully authenticated
--> Retrieving additional user info failed!
Traceback (most recent call last):
  File "/home/dsmits/anaconda3/envs/verticox/lib/python3.9/site-packages/vantage6/client/__init__.py", line 613, in authenticate
    id_ = jwt.decode(self.token,
KeyError: 'sub'
```

I still have the old version of the vantage6 server (`3.2.0`) so it could be that. But I wanted to report this just to be sure.

**To Reproduce**
```python
>> client.authenticate(username, password)
>> client.setup_encryption(private_key)

**Expected behavior**
I expected no errors

**Details**
 - OS: Ubuntu 18.something
 - Version: client: `3.3.0`, server: `3.2.0`

**Comment by frankcorneliusmartin** [comment]
Thanks Djura for reaching out. It turns out that client and server `3.2.0` and `3.3.0` are not compatible because of the upgrade, see #227, #10 and #277. This most likely will also be the case for the node and server.

This can be fixed by checking which key is present in the dictonary.

**Comment by frankcorneliusmartin** [comment]
These fixes should be removed in version 4+

**Comment by dsmits** [comment]
Thanks! I will make sure to align the client and server versions in the future
