### ISSUE TITLE
[Change Request] Add logging for each endpoint request at the server

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#295]
**Description**
Not every endpoint writes log messages if it is called in an appropriate manner (it only writes warnings/errors if it is called wrongly). Sometimes, it is informative to check the server logs to see which endpoints have been called. Therefore, the idea of this change request is to add a log message on a generic place for all endpoints saying that that particular endpoint has been called.
Note that there should *not* be a message for non-existing endpoints.

**Comment by frankcorneliusmartin** [comment]
Why not use the `url` property over the `url_rule`?

i.e.

https://github.com/vantage6/vantage6/blob/9a5dcdb2544f9eea25b06eb701f8b8bf201ed3f2/vantage6-server/vantage6/server/__init__.py#L208

```python
log.debug(f"Received request: {request.method} {request.url}") 
```

Now we see the rule, but not the resource (id) that has been accessed.
