### ISSUE TITLE
Configure vantage6 to use a proxy server

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#3]
We need to create a few additional configuration settings (and flags for `vnode`):

`HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`, see https://docs.docker.com/network/proxy/

To test locally we can use: https://www.youngzsoft.net/ccproxy/proxy-server-download.htm

**Comment by dsmits** [comment]
@frankcorneliusmartin @bartvanb does this still need to be implemented or has it already been done? A project partner of mine got instructions from someone else (outside of IKNL) to put the proxy settings in the node config

**Comment by frankcorneliusmartin** [comment]
This can be done outside of the vantage6 infrastructure, see:
