### ISSUE TITLE
[Bug] `CRITICAL - Could not refresh token`

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#306]
**Describe the bug**
When I deploy my nodes everything seems to run great for a while, but after a while I get an `Exception: Authe ntication Error!`. The entire trace can be seen in the screenshot.

I had it yesterday and the screenshot is from Florian today.

**To Reproduce**
1. I'm currently not using encryption (see #305)
2. (Re) Start your nodes
3. Run an algorithm like `harbor.carrier-mu.src.surf-hosted.nl/carrier/n2n-diagnostics`
4. See that it succeeds
5. Wait a day or two
6. Run the same algorithm
7. Witness the error message

- The problems were seen on the following algorithms (I would recommend testing with n2n-diagnostics):
  - `harbor.carrier-mu.src.surf-hosted.nl/carrier/n2n-diagnostics`
  - `harbor.carrier-mu.src.surf-hosted.nl/carrier/verticox`
  - `harbor.carrier-mu.src.surf-hosted.nl/carrier/vertibayes`

**Expected behavior**
I expected the algorithm to run succesfully 

**Screenshots**
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/131889/189883923-9743c4e2-9dcf-499f-8d73-25cd2f3003cb.png)

**Details**
- vantage6 version 

**Additional context**

**Comment by frankcorneliusmartin** [comment]
The refresh token mechanism is broken. After some digging I found that `flask_jwt_extended` added a few reserved payload keys: 

https://github.com/vimalloc/flask-jwt-extended/commit/bcb9459b94da80bd4abcc6f24f53787d6d030b3a

We use the `type` key for indicating if the auth a user or node is. This conflicts with the type used by flask_jwt_extended which use that key to indicate if it is a `access` or `refresh` key.
