### ISSUE TITLE
[Feature Request] Hard coded email adresses 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#319]
**Problem description**
The server has several hard coded emails. 
* https://github.com/vantage6/vantage6/blob/main/vantage6-server/vantage6/server/templates/mail/reset_password_token.html
* https://github.com/vantage6/vantage6/blob/9d4d043c6069538bbd74543666b4dd873dc283fc/vantage6-server/vantage6/server/resource/recover.py#L190
* `/token/user` 

**Desired solution**
Make this a setting in the configuration file.

**Comment by frankcorneliusmartin** [comment]
I dont really know.. 

Only thing i missed in my list is the default value for `MAIL_USERNAME` in the server init.

**Comment by bartvanb** [comment]
In that case, I guess `/token/user` is fine like this.

The `MAIL_USERNAME` is covered as well in the PR.
