### ISSUE TITLE
[Bug] Empty values in PATCH `/user/<id>` are not propagated to database

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#334]
**Describe the bug**
If we do a PATCH `/user/<id>` and update a field with empty value, that field is not updated in the database.
E.g. if a user has firstname 'Alice' and we try to edit that to '' (empty string), the firstname will not be updated.
Similar for other fields in the user endpoint.
We should also check whether this may be the case for other PATCH endpoints.

**Expected behavior**
If someone wants to put an empty string in a PATCH request, that should be done (given that it's allowed for that field)

**Details**
 - v6 version 3.3.7

**Comment by frankcorneliusmartin** [comment]
Becareful to not confose `None` with "". As then all the fields that you do not set are whiped
