### ISSUE TITLE
[Bug] Separate containers on same node cannot talk to eachother over n2n

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#336]
**Describe the bug**
It is impossible to reach a separate algorithm container that is running on the same node using n2n communication.

When triggering a task on the same node it is possible to get the ip and port number back. However, they containers will not be able to connect.

**To Reproduce**
A simple way to check this is to use the n2n diagnostics algorithm.

This should run correctly:
```python
# Get organizations
active_nodes = client.node.list(is_online=True)
active_nodes = active_nodes['data']
org_ids = [n['organization']['id'] for n in active_nodes]

# Pick one node to run as master algorithm
master_node = org_ids[0]

# Pick the nodes that it should connect to
# In this case the organization of the master node is excluded
other_nodes = org_ids[1:]

n2nclient = N2NDiagnosticsClient(client)
task = n2nclient.echo(master_node, collaboration_id, other_nodes)

# Wait for results, etc.
```
The following will give an error:
```python
# Get organizations
active_nodes = client.node.list(is_online=True)
active_nodes = active_nodes['data']
org_ids = [n['organization']['id'] for n in active_nodes]

# Pick one node to run as master algorithm
master_node = org_ids[0]

# Pick the nodes that it should connect to
# In this case the organization of the master node is *included*
other_nodes = org_ids

n2nclient = N2NDiagnosticsClient(client)
task = n2nclient.echo(master_node, collaboration_id, other_nodes)

# Wait for results, etc.
```

**Expected behavior**
Connecting to an algorithm container on the same node should behave the same as connecting to a separate node.

**Details**
- Version: `node: '3.3.7', cli: '3.3.6'`

**Additional context**
Discussed with @frankcorneliusmartin

**Comment by dsmits** [comment]
I want to look into this myself (unless @bartvanb  or @frankcorneliusmartin suddenly have some spare time that they don't know what to do with ;) )

I'll assign it to me

**Comment by dsmits** [comment]
@bartvanb @frankcorneliusmartin I'm gonna have a look today

**Comment by dsmits** [comment]
I just found that I can make the communication between algorithms work if I add some NAT rules specifically for the local case.

You will need to add another port mapping rule to redirect traffic from the local interface, not just from `tun0`.
In my case the eth1 interface conntects to the isolated docker network.

The first rule mimics the port mapping rule. The second one mimics the MASQUERADE rule that was already there.

```
iptables -t nat -A PREROUTING -d LOCAL_VPN_IP -i eth1 -p tcp -m tcp --dport LOCAL_ALGORITHM_PORT -j DNAT --to-destination LOCAL_ALGORITHM_IP:PORT
iptables -t nat -A POSTROUTING -s 172.29.0.0/24 -d 172.29.0.0/24 -j MASQUERADE

```

**Comment by dsmits** [comment]
Now I'm thinking you might have to add the following rule as well, it was also present in my test setup:
```
iptables -A FORWARD -i eth1 -o eth1 -j ACCEPT
```

**Comment by bartvanb** [comment]
Just tested this with release candidate 3.8.0rc3: it seems to be working. For future reference, this is what I did:

I ran the `test_on_v6.py` script from v6-node-to-node-diagnostics. I pulled the newest versions so that it includes [this change](https://github.com/vantage6/v6-node-to-node-diagnostics/blob/9cd3aec09f3c747f6a642a99cfe996f8fe8dcce7/test_on_v6.py#L35) which makes it also ping to an algorithm container on the node itself.

From running `test_on_v6`, I got the following output bit:

```
info > Dispatching node-tasks to organizations [1, 2]
info > Waiting 5 seconds for the algorithm containers to boot up...
info > Polling results for port numbers...
info > []
info > Polling results for port numbers...
info > []
info > Polling results for port numbers...
info > []
info > Polling results for port numbers...
info > [{'ip': '10.76.0.160', 'port': 49153, 'label': None}]
info > Polling results for port numbers...
info > [{'ip': '10.76.0.159', 'port': 49154, 'label': None}, {'ip': '10.76.0.160', 'port': 49153, 'label': None}]
info > Echoing to 2 algorithms...
info > Sending message to 10.76.0.159:49154
info > Checking echo on 10.76.0.159:49154
info > Timeout! Skipping to next address.
info > Sending message to 10.76.0.160:49153
info > Checking echo on 10.76.0.160:49153
info > Succeeded echos: [True]
```

It shows that it's echoing to 2 algorithms running on 2 different nodes (visible from the different IP addresses). I only have 2 nodes running for this server so it has to be that the central algorithm is echoing to a child on the same node. The logs show that this succeeds

@dsmits thanks, works really nicely :-)

**Comment by dsmits** [comment]
@bartvanb the echo is succeeding on 1 of the 2 algorithms. Shouldn't they succeed on both algorithms if n2n is working between algorithms on the same node?

**Comment by bartvanb** [comment]
Wow you're absolutely right. I guess I read past it - or maybe I copied the wrong logs.

Anyhow, I just tested it again and it's working now:
```
info > [{'ip': '10.76.0.159', 'port': 49157, 'label': None}, {'ip': '10.76.0.160', 'port': 49153, 'label': None}]
info > Echoing to 2 algorithms...
info > Sending message to 10.76.0.159:49157
info > Checking echo on 10.76.0.159:49157
info > Sending message to 10.76.0.160:49153
info > Checking echo on 10.76.0.160:49153
info > Succeeded echos: [True, True]
info > Writing output to /mnt/data/task-000000013/output
```
