### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by stefan-wolfsheimer** [vantage6/vantage6#338]
**Describe the bug**
Related to bug https://github.com/vantage6/vantage6/issues/333:

The API endpoint is now accepted, but the `change_my_password` has no effect. 

**Step To Reproduce**
```
client.authenticate("root", ORIG_ROOT_PASSWORD)

client.util.change_my_password(ORIG_ROOT_PASSWORD, ROOT_PASSWORD)

client.authenticate("root", ROOT_PASSWORD)
```

**Expected behavior**
The new password should be valid in the second authentication.

**Screenshots**
```
Traceback (most recent call last):
  File "set_root_password.py", line 47, in <module>
    client.authenticate("root", ROOT_PASSWORD)
  File "/opt/vantage6/lib/python3.8/site-packages/vantage6/client/__init__.py", line 604, in authenticate
    super(UserClient, self).authenticate({
  File "/opt/vantage6/lib/python3.8/site-packages/vantage6/client/__init__.py", line 317, in authenticate
    raise AuthenticationException("Failed to authenticate")
vantage6.common.exceptions.AuthenticationException: Failed to authenticate
```

**Comment by stefan-wolfsheimer** [comment]
My bad: The change password function silently fails (without exception) if the password is not compliant. I should have checked the return.

**Comment by frankcorneliusmartin** [comment]
Not sure if you are aware already but it can be helpful to enable some additional logging: 
`Client(...., verbose=True)`

For now it is not possible to set different levels in the logging. So its everything or nothing.
