### ISSUE TITLE
[Change Request] Remove deprecated function from pipeline

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#342]
**Description**
![image](https://user-images.githubusercontent.com/15981243/195567731-500ac0f2-fcf3-4aba-93ad-585790cb995d.png)

**Comment by bartvanb** [comment]
Check if this is still relevant

**Comment by bartvanb** [comment]
I just found in the [release notes of 3.9.0](https://docs.vantage6.ai/en/main/release_notes.html#id66) that this function has been removed back then
