### ISSUE TITLE
[Feature Request] MFA

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#355]
**Problem description**
To comply with the NEN7510 it is required that we have at least 2FA. 

**Desired solution**
- Optional MFA 
- vantage6 server owner can configure which level (maybe even let the users decide?)
- Email
- Token

**Additional context**
Miguel (we use his socketio library) has wrote a nice blogpost about this: https://blog.miguelgrinberg.com/post/two-factor-authentication-with-flask

**Comment by bartvanb** [comment]
Decisions made:
- we will support email and totp
- Whether or not MFA is enabled is set by server admin and applies to all users (this is e.g. required for Dutch NEN norms)

Starting with totp implementation

**Comment by frankcorneliusmartin** [comment]
Tested, lgtm. 
Added issue #405
