### ISSUE TITLE
[Feature Request] Add citation to log

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#356]
**Problem description**
It would be good to remind authors to cite our papers in the case they publish using vantage6.

**Desired solution**
- Add a log line when the node is started 
- Add a log line when the client is initialized

> If you publish your findings obtained using vantage6, please cite the proper sources as mentioned in https://vantage6.ai/vantage6/references/

**Comment by bartvanb** [comment]
Fixed in #359
