### ISSUE TITLE
[Feature Request] Extend API to enable pagination in UI

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#392]
**Problem description**
We would like to use pagination in the UI to make everything go a lot faster, but we're missing some things on the API to make that change. This should be included in v4.

Features that we definitely need:
- some type of `include` argument where you include complete resources. E.g. `/node?include=collaboration,organization` should yield the node with inside the full json of the organization and collaboration. (Note that this could lead to difficult authorization checks)
- A `count` option to get the total number of resources without needing to get them all fully

We should consider if these are all necessary features, or if there are more

**Comment by bartvanb** [comment]
After rethinking this, we want to go a different way

- No `include` arguments as this leads to complicated permission checks and potentially unlimited nestings
- The `count` option is already there: it's just 'hidden' in the headers

Instead, we should:

- [ ] Adapt the API so that **everything** is **always** paginated
- [ ] Adapt the UI to go through all the pages whenever necessary

**Comment by bartvanb** [comment]
Relevant branch: `change/always-pagination`
For UI: `feature/pagination`

**Comment by frankcorneliusmartin** [comment]
🔴 

From the client:
```python
>>> len(client.organization.list(per_page=2)['data'])
Making request: GET | http://localhost:5000/api/organization | {'page': None, 'per_page': 2, 'name': None, 'country': None, 'collaboration_id': None}
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "GET /api/organization?per_page=2 HTTP/1.1" 200 5562
6
```

A more basic requests yields the same:
```python
>>> len(client.request('organization', params={'per_page':2})['data'])
Making request: GET | http://localhost:5000/api/organization | {'per_page': 2}
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "GET /api/organization?per_page=2 HTTP/1.1" 200 5562
6
```

**Comment by frankcorneliusmartin** [comment]
Interestingly enough this *does* work for the `client.node.list(.)` function / endpoint
