### ISSUE TITLE
[Change Request] Users should not be able to change usernames of other users

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#396]
**Description**
It doesn't make sense for users to change usernames of other users so we should make that impossible. 

Optionally, we could completely fix usernames so that they cannot be changed after they are created. But that might make more sense when users register themselves (as proposed in #372)

**Comment by frankcorneliusmartin** [comment]
Well maybe as a super admin you do want to do this? Maybe when someone has an offensive name?

**Comment by bartvanb** [comment]
I would prefer to keep it like this, as I think it is very confusing if a user's username has been changed without their knowledge, and its a much more likely scenario than offensive usernames (or am I being naive :')).
If someone has an offensive name and refuse to change it, their user may simply be deleted?
