### ISSUE TITLE
[Feature Request] Support other file extensions for filebased databases on the node

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#397]
**Problem description**
When you start the node with a file based database that is not .csv the infra will change the file extension. E.g. `database.xslx` becomes `label.csv` (with `label` the label specified in the configuration file).

**Desired solution**
Dont alter the extension.

Found by: @anjavangestel, @dsmits

**Comment by bartvanb** [comment]
What's important to keep in mind here, is that we currently have restrictions specific to csv file extensions to prevent data leakage. These restrictions should be updated when this is modified.

**Comment by dsmits** [comment]
I guess this issue can be closed?

**Comment by bartvanb** [comment]
Hi @dsmits, we haven't closed it yet because it hasn't been released. We've merged a fix in the dev3 branch which will eventually be released into 3.6.
You can check our progress on 3.6 [here](https://github.com/orgs/vantage6/projects/1/views/13)
