### ISSUE TITLE
[Feature Request] Multi database wrapper

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#398]
**Problem description**
All current database wrappers read one database file and pass that on to the algorithm. Some algorithms may want to use several databases and doing so would require a new wrapper that looks something like this:

```
class MultiDBWrapper(WrapperBase):
    @staticmethod
    def load_data(database_uri, input_data):
        data = {}
        for uri in database_uri:
            data[uri] = pandas.read_csv(database_uri)
        return data
```

Requested by @anjavangestel

**Comment by bartvanb** [comment]
Hi @fvandaalen, I fear I completely missed your comment. Indeed, we should preserve the file extensions, and in fact we have a separate issue open for that: #397.
Both that issue and this one are scheduled for 3.6, which we will release either this week or next week.

**Comment by fvandaalen** [comment]
Great, then we can remove our workarounds soon.
