### ISSUE TITLE
Nodes appear to be offline

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#40]
If the server reboots, the nodes status field is not set properly when using multiple workers. It seems likely that the `start()` method is triggered after some of the clients (=nodes) reconnected. 

Reported by @anjavangestel

**Comment by bartvanb** [comment]
Did some (preliminary) investigation. 
It may not be such a bad idea after all to store the status in the database: it is not trivial to retrieve this information (see e.g. [here](https://stackoverflow.com/questions/62893437/how-do-i-list-all-connected-clients-in-flask-socketio)). The option to prevent database storage appears to be to store the connected clients in some global variable like [here](https://stackoverflow.com/questions/26908675/flask-socketio-namespace-keyerror-get-list-of-connected-clients) but then I'd prefer to just keep it in the database.

**Comment by bartvanb** [comment]
Instead of the earlier proposal, I now simply moved the code that set the nodes to offline to a place before the socket is initialized. This should guarantee that the correct state is stored in the database. However, we should still test this after deployment

**Comment by frankcorneliusmartin** [comment]
This does not resolve the issue. When a server instance is initialized, all nodes statusses are set to `offline`. Thus if a single worker reboots all nodes are set to offline even though some of the workers might be still up and running. These other workers might have active and healthy socket connections and therefore these nodes will not reattempt to reconnect. Thus these nodes will appear to be offline while in practice they are still properly connected.

We also cannot simply skip the server initialization step that sets these nodes to the status offline. This would mean that nodes that do get disconnected because of a failing worker will appear online but are in reallity offline. 

Therefore I propose to obtain the status directly from the active socket connections. Or drop this field entirely (which @anjavangestel  will probably hate).

**Comment by frankcorneliusmartin** [comment]
It seems not to be trivial to retrieve the connected clients from the socketio server, see: https://stackoverflow.com/questions/62893437/how-do-i-list-all-connected-clients-in-flask-socketio

I also posted a question to the author of the `flask_socketio` package, I hope he can push us in the right direction.

**Comment by bartvanb** [comment]
The plan we have now come up with should fulfill the following:

- [ ] There should be a ping from the server to all nodes once every minute
- [ ] Nodes that respond are set to online
- [ ] Nodes that do not respond and currently have a status of online, should be set to offline
- [ ] Nodes that are coming online should be able to have their status changed through other socket events
- [ ] Nodes that crash may have their status set to 'offline' after 30s but they may then be online again (if they're restarted immediately). This should go well
