### ISSUE TITLE
[Change Request] Parquet support documentation

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#401]
**Description**
We have parquet support now but we don't have documentation on it.

As I created the feature I propose I add the documentation.

**Comment by bartvanb** [comment]
Hi Djura, to get you started:
we are working on the (technical) documentation on branch feature/sphinx_documentation. See [here](https://tech-docs.vantage6.ai/en/main/devops/documentation.html#technical-documentation) for more info on how to run it locally.

**Comment by dsmits** [comment]
@bartvanb  This one can be closed right?

**Comment by bartvanb** [comment]
Yeah it's not live yet because it's still in a separate doc branch but we plan to merge that this or next week again. I will close this now
