### ISSUE TITLE
[Feature Request] `vnode new` should retrieve collaboration info from the server

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#434]
**Problem description**
To configure the node with the command `vnode new` the user needs to fill out a lot of details which can be retrieved from the server. Sometimes it is not clear that the settings should be in sync with the settings at the server (e.g. encryption). We should consider these options as collaboration policies and retrieve them from the server. This could also help in the future as we want to have privacy policies per algorithm (e.g. min number of patients). 

**Desired solution**
Simplify the `vnode questionair`.

1. _server url and port_
2. _api-key_
3. --> retrieve collaboration policies/settings from the server
4. private key (only when the collaboration encryption policy is enabled)

**Comment by bartvanb** [comment]
There should be a `vnode update` command that can be called to update these settings
