### ISSUE TITLE
[Change Request] Algorithm decorators

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#440]
**Description**
In the algorithms, there are a couple of methods that we want to rename. The best is to do this in v4.0, so that we don't face compatibility issues later. Renames should include:

- [x] ~~ The central methods should get a prefix `central_` ~~
- [x] The central method should not be named `master` anymore
- [x] The local methods should get a different prefix than `RPC_` as that is unclear (maybe simply `local_`)

Note that this list is not exhaustive: 
- [x] when implementing, consider other name changes

**Comment by frankcorneliusmartin** [comment]
Instead of prefixes we could also consider using:
```python
@data 
@client
@socket
def method(.):
    pass
```

**Comment by bartvanb** [comment]
Note that with the above, we will be letting go of the distinction between 'master' and 'RPC' methods, so there would no longer be a need for the prefixes

**Comment by bartvanb** [comment]
- [ ] make it suitable for using multiple databases in one algorithm run

This should be done by giving an argument to the decorator, that should somehow be fed back to the way in which the algorithm is called

**Comment by frankcorneliusmartin** [comment]
Lets test this when we create our first algorithm

**Comment by frankcorneliusmartin** [comment]
I tested this using the average:v4 algorithm the `@data` and `@algorithm_client` decorators work as expected.
