### ISSUE TITLE
[Feature Request] Hierarchy in scope for rule assignment

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#443]
**Problem description**
If a user creates another user or modifies the permissions of another user, they are only allowed to assign rules to that user that they also have themselves. So currently, if you want to give a user permission to edit roles for their organization, you need to be allowed to do that yourselves. 
But let's say I have permission to edit roles globally, then it's weird I'm not allowed to assign someone permission to assign roles for their organization, just because I don't have the exact same rule.

**Desired solution**
Introduce a hierarchy in allowing rule assignment. 
If someone has collaboration scope access, they should be allowed to assign organization scope access.
If someone has global access, they should be allowed to assign collaboration or organization scope access.

**Additional context**
Implementing this might impact the visualization of rules in the UI. E.g. if you select a global scope somewhere, the matching organization scope should also be selected.

**Comment by bartvanb** [comment]
Moved this to 4.0 as it becomes important with collaboration scope. We can then remove a bunch of rules from the default rules that they don't need because they have higher scope rules

**Comment by frankcorneliusmartin** [comment]
✅ 
1. made a new user with collaboration admin role
2. remove rule 21 (view organization, for scope organization), user still had collaboration and global scope
3. made new user without any permissions
4. loggied in as the collaboration admin \
5. assigned rule 21 to the new user without any permissions
6. User has now rule 21

✅ 
1. removed rules from the sad user again
2. logged in as the sad user
3. tried to assign the rule which failed
