### ISSUE TITLE
[Change Request] Support release branches in Github actions

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#467]
**Description**
* Currently the version tag is applied in the code and commited in the main branch. This blocks us to release from different branches 
* Maybe there are other issues also

**Comment by bartvanb** [comment]
We should probably create the release branch in the Github Action pipeline

**Comment by frankcorneliusmartin** [comment]
Idea:

* pre-releases should be build from the dev3 branch
* only releases on the main branch

Pipeline should be able to accomodate the pre-releases from the dev3 branch (especially the version commit)

**Comment by frankcorneliusmartin** [comment]
Pipeline failed for 3.9, see: https://github.com/vantage6/vantage6/actions/runs/4916657216
