### ISSUE TITLE
[Change Request] Replace `set-output` method from the Github actions

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#474]
**Description**
Github actions complains about some of the commands we use:

```
[github-release](https://github.com/vantage6/vantage6/actions/runs/3900643513/jobs/6661546997)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: marvinpinto/action-automatic-releases@latest. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

**Comment by bartvanb** [comment]
Fix for 1 of the 4 warnings in the linked PR.

The rest seems to be related to the action from 'marvinpinto' we're using. There is an open PR there that would probably solve the deprecation warnings: https://github.com/marvinpinto/action-automatic-releases/pull/2/files
