### ISSUE TITLE
[Change Request] HTML mail template for reset password isn't fluid

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#475]
**Description**
Resulting in a horizontal scrollbar:

![image](https://user-images.githubusercontent.com/15981243/212039968-dfc90b30-e2a6-4d80-8289-0407b2a920ad.png)

**Comment by bartvanb** [comment]
Found out that this is a problem specific to Microsoft Outlook - see below a screenshot of the gmail version. After discussing with @frankcorneliusmartin we decided to close this as it is not important enough to fix.

![image](https://user-images.githubusercontent.com/10533678/224760532-cabcae58-8e89-473b-b63c-0f978ddcbc8b.png)
