### ISSUE TITLE
Queries are becoming slow when many tasks/results are in the database

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#49]
When querying the endpoint `/organization/<id>` the query time is dependant on the number of tasks that belong to this organization. We should look into why this is the case (its not a super complicated query, but sqlalchemy can do some weird things) and/or implement measures to limit the number results.

This has been observed in `Harukas` but also likely occurs in `Petronas` (even though a lot of queries have been rewritten)

**Comment by bartvanb** [comment]
We will implement this in v4 by not listing all results and their separate routes, but rather one API link to getting all the results

**Comment by bartvanb** [comment]
- [ ] If there is a list of linked resources, provide path to get the list instead of the entire list
- [ ] Update the `marshmallow` dependencies to latest(?) versions
- [ ] Update the schema code to be more readable

**Comment by frankcorneliusmartin** [comment]
✅ Checked that the `/organization/<id>` endpoint no longer is dependent on the number of tasks.
