### ISSUE TITLE
[Feature Request] Option to list only parent tasks

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#583]
**Problem description**
I'd like a filter option on the get `/task` endpoint that allows me to get only tasks with no parents. This would e.g. allow filtering subtasks out of the UI more easily.

**Desired solution**
- [x] Have option to only get main tasks from GET `/task`
- [x] Also have this option in the Python client
- [x] Also use this option in the UI (people can still see subtasks by going to the parent task and then click on the subtask)
- [x] Consider an option to only get subtasks?

**Comment by frankcorneliusmartin** [comment]
Tested using the client, output is correct for: 
`client.task.list(fields=('id','name', 'status'), user_created=True)`
`client.task.list(fields=('id','name', 'status'), user_created=False)`
`client.task.list(fields=('id','name', 'status'))`
