### ISSUE TITLE
[DOC] Add RPC description

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#608]
**Description**
I am trying to setup a Python algorithm and am reading the following page:
https://docs.vantage6.ai/en/main/user/pyclient.html

This refers to RPC methods, but it does not describe what they are of how they need to be created. Also, it is not mentioned in earlier sections.

Can the documentation be updated with:
* what RPC stands for and why it is needed
* how to create an RPC method
* how the vantage engine knows that there is an RPC method and how it fetches it for task execution

**Comment by bartvanb** [comment]
Hi Harm, 

Agree that this is confusing, will update accordingly.

For now, you may find this info elsewhere in the docs, in [algorithm concepts](https://docs.vantage6.ai/en/main/algorithms/concepts.html#federated-function) and [the old algorithm tutorial](https://docs.vantage6.ai/en/main/algorithms/classic_tutorial.html#init-py).

Note also that in v4, we will get rid of RPC methods - the distinction we currently have between the 'central' algorithm and the federated/RPC parts is not necessary any more at this level.
