### ISSUE TITLE
[Feature Request] Option to include ssl server certificate in node

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#612]
**Problem description**
I am currently trying to connect to a vantage6 server that unfortunately doesn't have an ssl certificate signed by a public CA. The node is not going to accept this. The best way to solve this is to make sure that the vantage6 server gets an ssl certificate that's signed by a publicly accepted CA but it is difficult in this case.

**Desired solution**
An option in the vnode cli to include a ssl server certificate. This server certificate should be added to the node container's 
`/usr/local/share/ca-certificates`

**Additional Context**
The reason we can't just use let's encrypt is that the machine where vantage6 is running has only a few ip addresses whitelisted for incoming (and probably also outgoing) connections. With let's encrypt there is a server that will need to reach my machine in order to verify it.

**Comment by dsmits** [comment]
I might be able to work on this myself

**Comment by bartvanb** [comment]
Hi Djura, can you update us on the status of this issue? We are currently in process of planning issues into sprints.

**Comment by dsmits** [comment]
In the end I solved it by asking the owners of the v6 server to create a public certificate so it wasn't a problem for me anymore.
