### ISSUE TITLE
[Bug] Super role not assigned  any rules in `vserver import`

### ISSUE THREAD

**Issue by intGRen** [vantage6/vantage6#634]
When running the `vserver import` cli-command to batch import configurations, even if a super-user is specified it is not assigned any rules. 

Fix: To update Super user role with appropriate rules. Look into root user when creating new server.

**Comment by bartvanb** [comment]
I just tested this and I don't see this issue. The super roles have all possible rules, so I'm closing this
![image](https://github.com/vantage6/vantage6/assets/10533678/bedf47d5-5e59-47f5-9108-aa0900b8b843)
