### ISSUE TITLE
[Change Request] Update base images

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#639]
**Description**
Update the docker base image to later versions. At least update `debian:10` (LTS ends june 2024) to a later version but also check the other docker files.

**Comment by bartvanb** [comment]
I'm moving this to v4.0 as `debian:10` is still supported for another year, so it's fine for v3: https://wiki.debian.org/LTS

We should update the ssh-tunnel and squid dockerfiles

**Comment by bartvanb** [comment]
Newer versions than debian 10 are not yet supported so can't use newer ones.
