### ISSUE TITLE
[Feature Request] Function `client.task.wait_for_completion` for AlgorithmClient

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#651]
**Problem description**
Algorithms now often have a block of code in the central part of the algorithm that is something like this

```
    task = client.get_task(task_id)
    while not task.get("complete"):
        task = client.get_task(task_id)
        info("Waiting for results")
        time.sleep(1)
```

However, this no longer works in v4 because tasks no longer have a property 'complete'. 

**Desired solution**

One option is to re-introduce the `task.complete` property, but it may be better to make a function in the AlgorithmClient that checks this for the algorithm developer.

**Comment by frankcorneliusmartin** [comment]
✅ Tested with the average:v4 algorithm
