### ISSUE TITLE
[Change Request] Remove log lines for getting a task

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#666]
**Description**
When I post a task and I am waiting for it to be complete I can use the following code:

```
  while not client.task.get(task["id"])["complete"]:
        sleep(10)
```

This now logs clutter lines to my console:
```
Making request: GET | https://petronas.vantage6.ai:443/task/2048 | {'include': None}
Starting new HTTPS connection (1): petronas.vantage6.ai:443
https://petronas.vantage6.ai:443 "GET /task/2048 HTTP/1.1" 200 472
```

Can the default setting be not to show these loglines?

Reason: the lines are for my usecase not informative.

**Comment by bartvanb** [comment]
I just tested this and indeed, by initializing the client as `client = Client(url, port, api_path, log_level='info')`, these debug messages are not shown. They are also not shown in node logs at info level of the log.

Also, note that we have a utility function `client.wait_for_results` that will also prevent that these messages are printed over and over again.
