### ISSUE TITLE
[Change Request] Remove decryption loglines from vnode default logging

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#667]
My vnode console is filled with statements like these:

```
2023-05-13 19:16:33 - client         - INFO     - Decrypting input
2023-05-13 19:16:33 - encryption     - INFO     - Decrypted shared key: b'\xyz'

```

They seem not relevant. Perhaps they should be removed or at least be put under a log level like DEBUG? 

Thanks for considering.

**Comment by frankcorneliusmartin** [comment]
I agree these can ben moved to DEBUG level

**Comment by bartvanb** [comment]
I'll move the second one to DEBUG. I can't find the first one, so I think that has been removed/changed already.

Change has been committed directly on `release/4.2`
