### ISSUE TITLE
[Change Request] Harmonize interfaces or split them more to avoid inconsistency bugs

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#669]
There are several places where the docs mention client.task.xyz, but "client" actually means various things, e.g. a UserClient instance, an AlgorithmClient instance or the module client. This is not always clear.

What adds to difficulty in implementation is that the interfaces of some of the methods are different. 

- client.task.create requires different arguments depending on what "client" is, but arguments that intend to do the same have different names, e.g. organizations versus organization_ids and input versus input_

- client.result.get requires a result_id in the UserClient, but a task_id in the AlgorithmClient, which was not straightforward to debug. Also, they return diffent things, for the UserClient it returns a dict, while for the AlgorithmClient it returns the result value

It would help if either the interfaces are harmonized, such that they are exactly the same, at places where it is helpful to not care about whether you have a userclient/algorithclient/module and are made more distinct at places where it *does* matter which type of client you are working with.

**Comment by bartvanb** [comment]
- [ ] Rename `client.result.get()` to `from_task` in AlgorithmClient
- [ ] Create new function `client.result.get()` in AlgorithmClient
- [ ] Create `class Run` in AlgorithmClient
- [ ] Harmonize input arguments between clients
- [ ] Also change new MockClient when changing the AlgorithmClient
