### ISSUE TITLE
[Bug] not clear where to use parameter `include_metadata` while using API

### ISSUE THREAD

**Issue by intGRen** [vantage6/vantage6#670]
Right now its not so intuitive to figure out that the parameter `include_metadata` needs to be toggled when accessing the API for instance 

`client.organization.list(fields=['id','name'])` is how we previously used the command but that doesn't work, instead we must include the above explicitly, `client.organization.list(fields=['id','name'],include_metadata=False)`. 

Since this is a toggle its probably easy to just have it be "False" by default unless specified, or a warning/message is raised when accessing API as above.

I think this isn't that high priority.

**Comment by frankcorneliusmartin** [comment]
In v4+ pagination is always on, this option is completely removed.
