### ISSUE TITLE
[Bug] Contribution guidelines for setting up vantage6 for development lead to an error 

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#696]
**Describe the bug**
Following the steps in the contribution guidelines leads to an error:
https://docs.vantage6.ai/en/main/devops/contribute.html

ERROR: No matching distribution found for vantage6-common==3.9.0.rc0

After investigation and discussing there are a few problems:
* the dependencies on vantage6-common are set dynamically which depending on maturity of the main branch towards the new release a situation can occur that the dependencies are not yet released, e.g. the 3.9.0.rc0 is not available on pip
* the setup instructions now only define how to setup the vantage6 package itself, whereas the makefile in the rootdirectory suggests that also the vantage6 dependencies (common, client, node, server) should be installed in dev-mode
* perhaps the call to make should be given instead? however, make is not by default available on Windows, it would make sense to point out how to install it as well

**Expected behavior**
Expectation is that the steps above lead to a working development environment

**Comment by frankcorneliusmartin** [comment]
Instruction is changed to `make install-dev`
