### ISSUE TITLE
[Change Request] Node should adapt the version it pulls

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#700]
**Description**
If a node is connecting to a server with version `x.y.z`, the node currently retrieves `x.latest`. However, we would like to change this to `x.y.latest`, as these are much more likely to be properly compatible.

- [x] Adapt pipeline to create also docker image that with `major.minor` which is always the latest of the patch versions
- [x] Adapt node to pull that one by default
- [x] Adapt docs
- [x] Add warning in the CLI if the node version is not equal to the CLI version
- [x] Check that CLI works if we can't connect to the server - node should still start if server is not running

**Comment by frankcorneliusmartin** [comment]
Seems to been lost in mergen 3.10 into 4.x: 

https://github.com/vantage6/vantage6/commit/7d76f4d5db31b5172573669c210eca311387b487

**Comment by frankcorneliusmartin** [comment]
✅ Works in v4.0.0a10
