### ISSUE TITLE
[Change Request] Refactor task creation code server-side for master algorithm

### ISSUE THREAD

**Issue by lsago** [vantage6/vantage6#742]
Hi @bartvanb, following up on the conversation from several days ago about centralized aggregator where you asked me to create this issue.

By reading [the code here](https://github.com/vantage6/vantage6/blob/version/3.10.4/vantage6-server/vantage6/server/resource/task.py#L444-L464), it looked like it would be impossible for a user to run the master algorithm on a node that is not their organization's node. But on further inspection it seems like that 'master' attribute is [never sent on the POST at that level](https://github.com/vantage6/vantage6/blob/version/3.10.4/vantage6-client/vantage6/client/__init__.py#L507-L514). It is sent I believe, but [inside the serialized `organizations.input`](https://github.com/vantage6/vantage6/blob/version/3.10.4/vantage6-client/vantage6/client/__init__.py#L503), which might or might not be encrypted. So, I guess at the moment the server can't control on which node the master algorithm is allowed to run.

Perhaps it would be nice if node administrators had granular control over which part of an algorithm is allowed to run on their nodes (master, partial or both). But at the moment I don't believe this feature exists, and as you said, the expected behavior now is that users should be able to arbitrarily choose where the master runs (IIRC). So, maybe it's best if we remove [this check for 'master' on the server](https://github.com/vantage6/vantage6/blob/version/3.10.4/vantage6-server/vantage6/server/resource/task.py#L444-L462)? Provided I haven't missed anything, which is not unlikely :)

**Comment by bartvanb** [comment]
Indeed it is common to define `master=True/False` within the input (see e.g. [here](vnetGateway_name_resource)). So I think your assessment is correct: the first code fragment which you refer to has no function and should be removed. I'll create a PR for that.

**Comment by bartvanb** [comment]
Regarding your point that it would be nice for node admins to control which algorithm parts may run on their node: agree! We aim to tackle that in the collaboration 'policies', but you may already create an issue for this specifically so that we keep it in mind

**Comment by lsago** [comment]
Thank you!

The node-admin control over which part of the algorithms is allowed to run was more of an afterthought to this issue, but sounds good, will create an issue to keep it in mind. In the meantime, is there already some code/documentation for the new 'collaboration policies' that I could check out?

**Comment by bartvanb** [comment]
No, there is not really any work done on the collaboration policies. At present, it is just an idea that we want to implement in the future, but there is no plan yet of how to achieve it exactly.
