### ISSUE TITLE
Endpoint arguments validation

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#76]
The `reqparser` from flask is depreciated and they recommend using marshmellow to handle validation of input arguments:
https://marshmallow.readthedocs.io/en/stable/examples.html#quotes-api-flask-sqlalchemy

This could/should be applied to all `POST` and `PATCH` endpoints.

**Comment by bartvanb** [comment]
Since this depends on marshmallow, we should implement #49 first because that will include a significant update of the marshmallow version we use

**Comment by bartvanb** [comment]
- [ ] collaboration
- [ ] task
- [ ] node
- [ ] organization
- [ ] account recovery
- [ ] vpn
- [ ] role
- [ ] authentication
- [ ] Make sure error messages are displayed in the UI

**Comment by frankcorneliusmartin** [comment]
✅ POST `/organization`
✅ POST `/collaboration`

#834 needs to be fixed. But since it is an single issue and has been added to the sprint 4 I move this issue to Done
