### ISSUE TITLE
[Change Request] Pre releases show as latest release on Github

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#793]
**Description**
![image](https://github.com/vantage6/vantage6/assets/15981243/3de5c04e-6985-4f61-99cf-778de73f2226)

These should be marked as pre-releases

**Comment by bartvanb** [comment]
![Image](https://github.com/vantage6/vantage6/assets/10533678/7930c60a-8f93-4eb4-a146-31e73bfbdfe3)

This is resolved on the `release/4.2` branch
