### ISSUE TITLE
Add waiting for results method

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#8]
Add something like this to the client:
```python
task_id = task.get("id")
task = requests.get(
  f"{url}{api_path}/task/{task_id}", 
  headers=headers
)
while not task.get("complete"):
	task = requests.get(
      f"{url}{api_path}/task/{task_id}",
  	  headers=headers
    )
  sleep(1)
```
Maybe we can also add support for the WS channel rather than the polling mechanism.

Also lets add a cool progressbar rather than the endless `wainting for results` print.
```python
import itertools
import threading
import time
import sys

animation =  itertools.cycle(['|', '/', '-', '\\'])
t = time.time()
for i in range(10):
    time.sleep(1)
    frame = next(animation)
    sys.stdout.write('\rWaiting (' + frame + f') {int(time.time()-t)}s')
    sys.stdout.flush()
sys.stdout.write('\rDone!                  ')
```

**Comment by bartvanb** [comment]
@frankcorneliusmartin I am waiting to implement this as I seem to remember you already have some code in a Jupyter Notebook that connects to a web socket and handles this. Let me know if that is the case or not

**Comment by bartvanb** [comment]
In the end, I implemented this via polling instead of websocket. The websocket version no longer really makes sense to me as the `wait_for_results` functionality is a synchronous process, while websocket notifications are async by nature.
