### ISSUE TITLE
[Change Request] Change POST task structure to allow for multiple databases

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#804]
**Description**
The JSON structure of POSTing tasks of relevant fields in v3 is as follows:
```
{
    "name": "name", ...
    "organizations": [
        {
            "id": 2,
            "input": {
               ....,
               "query": "SELECT * from table"
            }
        }
    ],
    "databases": [
        "my_database_label",
        "my_second_db_label"
    ]
}
```

The problem with the above is that you can only define 1 query, but if you have two databases (and both are SQL), you need two queries. 

**Suggested solution**

Change to:
```
{
    "name": "name", ...
    "organizations": [
        {
            "id": 2,
            "input": {
                ...
		databases": [
		    {
		        "label": "some_label",
                        "query": "SELECT * FROM mytable;"
		     },
		    {
		        "label": "some_other_label",
                        "query": "SELECT * FROM my_other_table;"
		     },
		]
            } 
        }
    ]
}
```

The added advantages of doing it like that is that it will be possible to send different queries to different organizations (convenient for vertically partitioned data) and that it is extendable if we need more args such as `query` for one DB

It would even be possible to send multiple queries to the same database (!)

**Comment by bartvanb** [comment]
Checklist
- [x]  Server - POST task
- [ ]  Docs
- [x]  Node - POST task
- [x]  Client - post task
- [ ]  UI - post task
- [x]  wrappers, decorators - handle changed input

**Comment by bartvanb** [comment]
The proposed solution above is tricky considering that the input may be encrypted. The databases can then not be read at the central server, which can therefore determine which databases a task uses. Then the node would have to decrypt the input when starting tasks to determine which databases they need to provide envvars for - which is a bit of a hassle.

Putting this on hold to discuss input encryption.

**Comment by frankcorneliusmartin** [comment]
tested using 

```python
client.task.create(collaboration=1, organizations=[1], image='hello-world', description='', input_={'some': 'input'}, databases=[{'label': 'henk', 'query': 'select * from table'}], name='hello')
```
Logs:
```text
Making request: GET | http://localhost:5000/api/organization/1 | None
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "GET /api/organization/1 HTTP/1.1" 200 1446
Making request: POST | http://localhost:5000/api/task | None
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "POST /api/task HTTP/1.1" 201 621
``` 

Output that has been send to the server:
```json
{'children': '/api/task?parent_id=2', 'init_org': {'id': 1, 'link': '/api/organization/1', 'methods': ['PATCH', 'GET']}, 'collaboration': {'id': 1, 'link': '/api/collaboration/1', 'methods': ['PATCH', 'DELETE', 'GET']}, 'databases': [{'label': 'henk', 'parameters': '{"query":"select * from table"}'}], 'description': '', 'job_id': 2, 'created_at': '2023-09-12T12:44:36.225732', 'results': '/api/result?task_id=2', 'name': 'hello', 'parent': None, 'init_user': {'id': 1, 'link': '/api/user/1', 'methods': ['PATCH', 'DELETE', 'GET']}, 'runs': '/api/run?task_id=2', 'status': 'pending', 'image': 'hello-world', 'id': 2}
```

I also checked the database using the shell, and observed the parameters are present:

```python
 db.Task.get(2).databases[0].parameters
```
