### ISSUE TITLE
[Feature Request] Add study concept

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#812]
**Problem description**
Allow users to create subsets of organizations within a collaboration and call these a study (within a collaboration). 
This is required as we want to use a single node for multiple studies (which have different organization configurations) and we do not want to create new collaboration and nodes for each of them.

In terms of security the node does not enforce the study concept. This means that if a data owner connected a vantage6 node in a collaboration it gives permission to run all studies within a collaboration. On the server we _can_ limit to which studies you can send tasks. 

This is related to the new policies system

**Comment by bartvanb** [comment]
- [ ] Add study model
- [ ] Add input and output schema's
- [ ] Implement endpoints
- [ ] Add endpoints to app
- [ ] Modify endpoints for task (and maybe collaboration and organization?)
- [ ] Implement unit tests
- [ ] Implement subclass Python client
- [ ] Modify task, collaboration and organization subclients
- [ ] Implement in UI
