### ISSUE TITLE
[Feature Request] `from vantage6.client import Client` alias missing 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#826]
**Problem description**
In previous version we could import the `UserClient` as an alias using:

`from vantage6.client import Client`

I would like to have this back.

**Comment by frankcorneliusmartin** [comment]
@bartvanb Missing PR?

**Comment by bartvanb** [comment]
Yes - fixed in https://github.com/vantage6/vantage6/commit/f36d6a24fd3b54b1883691282ba4c5788696c1e2 and pushed without PR by accident
