### ISSUE TITLE
[Bug] When using the test server `client.collaboration.list()` produces a 404

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#827]
**Describe the bug**
A fresh `vdev create-demo-network` server produces a 404 on retrieval of the collaboration list.

```python
from vantage6.client import UserClient
client = UserClient('http://localhost', '5000', '/api', log_level='debug')
client.setup_encryption(None)
client.collaboration.list()
```
produces:
```text
pagination for scope `organization` not available
Making request: GET | http://localhost:5000/api/organization/4/collaboration | None
Starting new HTTP connection (1): localhost:5000
http://localhost:5000 "GET /api/organization/4/collaboration HTTP/1.1" 404 207
Server responded with error code: 404
Did not find a message from the server
```

I think this happens because the `root` organization is not participating in any collaboration. However this should then result in an empty list.

**Details**
 - version 4.0.0a7

**Comment by bartvanb** [comment]
Yes, fixed in https://github.com/vantage6/vantage6/commit/f36d6a24fd3b54b1883691282ba4c5788696c1e2 and pushed without PR by accident
