### ISSUE TITLE
[Feature Request] Store dashboard configuration in database

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#858]
**Problem description**
In the researcher UI it is tedious and error prone to fill in the new task form every time for a similar or identical task. Therefore I would like to store a JSON(?) blop in the database which contains the configuration of this dashboard. One of the configuration options should be a reference to a *template task* see issue #857.

The dashboard should be coupled to a collaboration (or maybe to a study #812?)

**Comment by bartvanb** [comment]
Duplicate of #857
