### ISSUE TITLE
[Feature Request] Add command `import-data` to `vdev` cli commands

### ISSUE THREAD

**Issue by intGRen** [vantage6/vantage6#860]
It would be nice to have this feature added to the `vdev` commands because it would further improve the automation aspect of the cli command, as well as assist algorithm development as users will be able to import the correct data to the data-stations via a command. 

We can do this by having the function, `vdev import-data` look in a certain directory for the data. It can then manually assign to each data-station a dataset. We might require a caveat that if it's important that each data-station be assigned the "correct" data that they be labelled accordingly. For instance if we have name "Node-Station-1" then the data must be called something along the lines of "data-1". Furthermore, it would be nice to have it accept multiple types; 'csv', 'xml', etc.

**Comment by bartvanb** [comment]
My thought on how this would work was as follows:

```
vdev create-demo-network
>>>
Do you want to add custom data (y/n)?
... (if yes, more questions about adding data)
```
or
```
vdev create-demo-network --data-file some_data.csv
```
(but then with multiple data files somehow)

I think that would be easier to implement since you can immediately add the database to the node config file, rather than updating a file afterwards. 
But a `vdev import-data` command also seems like a good idea, maybe we can do both.

**Comment by intGRen** [comment]
Yeah I agree with you, let's start with the first option!

**Comment by frankcorneliusmartin** [comment]
Let me note that if we want to use it for integration test we need to command line option also

**Comment by bartvanb** [comment]
Perhaps it would also be an good idea to be able to do:

```vdev create-demo-network --extra-server-config some_partial_server_config.yaml --extra-node-config some_partial_node_config.yaml```

That would 
1) enable you to add one or more databases if your yaml file looks something like
```
databases:
    - label: some_db
      url: my.csv
      type: csv
```

2) But it would also allow you to include stuff like VPN server configuration into the servers and nodes

What we do have to take into account there is that we have multiple nodes so we may need separate configs for them

**Comment by bartvanb** [comment]
There are a few other small things I'd like to include here that don't really merit their own issue. To make a full todo list:

- [ ] `vdev create-demo-network --extra-server-config some_partial_server_config.yaml --extra-node-config some_partial_node_config.yaml`
- [ ] With `vdev remove-demo-network`, don't ask for confirmation to remove the server
- [ ] If `vdev remove-demo-network` fails somewhere, it should not stop execution. Now I am sometimes left with half a demo network left
- [ ] Same goes for `create` 
- [ ] Assign usernames and passwords to the demo network
- [ ] maybe a `vdev -f remove-demo-network` that first stops network and then removes it (just like `docker remove -f`)

Feel free to not include these items in this issue - then we should just make sure to create separate issues.

**Comment by bartvanb** [comment]
Rest of issues is transferred to issue mentioned above, so we can close this when upcoming PR is released
