### ISSUE TITLE
[Change Request] CLI `--config` flag requires full path to YAML file

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#870]
**Description**
If you provide a custom location for a config file, e.g. `vserver start -c myconfig.yaml`, the YAML file requires a full path. It would be nicer if it only requires a correct path.
This probably should also be changed for `vnode` commands.

Right now there is an error, as reported by Severin Elvatun in Discord:
![image](https://github.com/vantage6/vantage6/assets/10533678/cb933f18-3e5b-444a-9c71-7619281cab2c)

**Comment by frankcorneliusmartin** [comment]
We should check if this is already fixed

**Comment by bartvanb** [comment]
It was already working correctly for server and algorithm store but not for node - see PR

**Comment by bartvanb** [comment]
![Image](https://github.com/vantage6/vantage6/assets/10533678/2dc0b30a-9824-4985-8c05-2eab679c6fd8)

When stopping the node (`v6 node stop` without other options) after starting it with `-c ../my/path.yaml` the message above is shown
