### ISSUE TITLE
[Bug] Test case error due to API authentication error

### ISSUE THREAD

**Issue by hcadavid** [vantage6/vantage6#913]
**Describe the bug**

When setting up a local development environment as described on https://docs.vantage6.ai/en/main/devops/contribute.html#local-test-setup, on MacOS, the _test_node_wizard_ is generating an authentication error (after running 'make test').

test_node_wizard (tests_cli.test_wizard.WizardTest.test_node_wizard)                  Failed to authenticate: Request body is incorrect
[error] - Could not authenticate with server: Failed to authenticate
[error] - Please check (1) your API key and (2) if your server is online

Before running the test suite, I started a local v6 server and checked that the API was working properly on port 5000.

**To Reproduce**
On MacOS:
1. Clone a clean copy of vantage6
2. Create and activate a venv
3. python -m pip install --upgrade pip setuptools
4. make install-dev
5. Get the server_config.yaml example from https://docs.vantage6.ai/en/main/_downloads/003b34f9b9537c069790be17cbcafc02/server_config.yaml
6. v6 server  start --mount-src */my_local_repo_path* --config */config_path*/server_config.yaml
7. make test

**Details**
 - OS: MacOS 12.5 (Mac M1)
 - Version 4.1.0
- Docker deamon version: 24.0.6

**Comment by frankcorneliusmartin** [comment]
Hi @hcadavid,

- I see that you are using the `--mount-src` option. This option is used to mount the vantage6 source inside the container. You only need that if you modified piece of code in the source and want to test it. It expects a path to where the root directory of the vantage6 source is. 
- Ill try to have a look at the unittest somewhere next week.
- Where you able to start a node and connect it to the server?

**Comment by hcadavid** [comment]
Hi @frankcorneliusmartin 

Yes, this is indeed what I want to do, setting up the environment where I can test changes on the server or the node code. I'm using the absolute path as you mentioned (my post had that part hidden due to the symbols I included :)), and the server seems to working correctly (it replies to a GET request on /api/version as expected).

**Comment by frankcorneliusmartin** [comment]
Nodes also connect properly? -> So only the `make tests` fail?

**Comment by frankcorneliusmartin** [comment]
@hcadavid is this still relevant?
