### ISSUE TITLE
[Bug] Documentation for UserClient.Task.create does not match api for parameter `input_`.

### ISSUE THREAD

**Issue by mellesies** [vantage6/vantage6#939]
**Describe the bug**
The documentation contains an error in the following snippet:
```
average_task = client.task.create(
   collaboration=1,
   organizations=[2,3],
   name="an-awesome-task",
   image="harbor2.vantage6.ai/demo/average",
   description='',
   input=input_,
   databases=[
      {'label': 'default'}
   ]
)
```

Here `input=input_,` should be `input_=input_,`

**To Reproduce**
1. Go to [the documentation](https://docs.vantage6.ai/en/main/user/pyclient.html#creating-a-task)
2. Scroll down to "Creating a task that runs the central algorithm"
4. See the snippet with the error.

The same omission may be found elsewhere in the docs. I suggest running `grep`.

**Expected behavior**
Documentation should match API.

**Screenshots**
The documentation with the error:
![image](https://github.com/vantage6/vantage6/assets/9558262/ac89413b-ff6d-4784-9840-0a8f870a30d7)

The API:
<img width="701" alt="image" src="https://github.com/vantage6/vantage6/assets/9558262/b1e315c4-6082-4ed0-aee1-3ccf36f10f3e">

**Details**
 - Version 4.1.2

**Comment by bartvanb** [comment]
Just fixed this, should be live in 10 min
