### ISSUE TITLE
[Feature Request] Authorization in the algorithm store

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#967]
**Problem description**
The algorithm store currently authorizes with a vantage6 server that is linked to. However, currently all users are allowed to perform the same actions. We therefore want to introduce a permission system.

Note that at present, not all endpoints have been implemented, so we can only create permissions for those that have already been created. The main goal of this issue is to create the permission *system*; other permissions can be added later as we go along.

**Desired solution**
To keep things simple, the permission system should be implemented in a similar manner to the permission system for the vantage6 server. This means that it should have the following features:

- Separate permission rules to create, view, edit and delete algorithms
- When an algorithm store is coupled to a store, permissions are provided to the admins of that server (? maybe other solution?)
- We can define roles that are collections of rules (same as v6 server)
- We define default roles: 
  - 'Viewer' can view only
  - 'root' can do everything
  - 'StoreManager' can view and delete
  - 'Reviewer' can view and edit
  - 'Developer' can view and create
- Users can assign permissions/roles that they have themselves to other users
- Unit tests
- Documentation similar to https://docs.vantage6.ai/en/main/server/permissions.html

Notes:
- probably the `PermissionManager` from the server can be partially reused (as well as some other code I think)
- In the vantage6 server, we have scopes (e.g. 'organization' and 'global') but those are not relevant here I think.

**Additional context**
Work in progress on algorithm store on branch `feature/algorithm-store`

**Comment by dsmits** [comment]
Tasks:
- [ ] Table for permissions
- [ ] Table for rules
- [ ] Figure permission manager
- [ ] Copy relevant parts permission manager from vantage6 server

**Comment by wbaccinelli** [comment]
After discussing with @CunliangGeng, we have some more considerations for the permissions system and, in particular the concept of reviewing an algorithm:
- A specific algorithm should be linked to a Developer and to a Reviewer.
- After the creation of an algorithm by a Developer, the Store Manager should be able to assign a reviewer to the algorithm.
- We should know what is the status of the algorithm is in the review process (e.g., draft, under review, approved, rejected). The default state is Draft.
- A reviewer should be able to change the status of the algorithms he/she is assigned to.
- A developer should be able to post modifications to the algorithms he/she created.

With this in mind, an option would be to add a new resource (ReviewProcess?) where we store the link between a reviewer and an algorithm and the status of the algorithm. This new resource will have its rules (Store Manager and Reviewer can edit, developer can view). 

@bartvanb does this make sense to you?

**Comment by bartvanb** [comment]
Good work, I agree with those considerations, with one exception: I think one algorithm may be linked to multiple reviewers. I can imagine algorithms should sometimes be reviewed e.g. by people of several organizations.

> With this in mind, an option would be to add a new resource (ReviewProcess?) where we store the link between a reviewer and an algorithm and the status of the algorithm. This new resource will have its rules (Store Manager and Reviewer can edit, developer can view).

I think that should be done as part of issue #981. That endpoint may also be the right place to put the logic that a reviewer can update the status of an algorithm but not the rest of its contents
