### ISSUE TITLE
[Bug] Can't start algorithm store with --user

### ISSUE THREAD

**Issue by dsmits** [vantage6/vantage6#978]
```
v6 algorithm-store start --user
```
Does not work.

I have created a config with `v6 algorithm-store new --user` but the config can't be found when doing `v6 algorithm-store start` or `v6 algorithm-store start --user`

I'm on the algorithm store feature branch

**Comment by bartvanb** [comment]
@dsmits I cannot reproduce this. Can you show the complete error message?

**Comment by dsmits** [comment]
I tried it again and I can't reproduce it either.
